version: "3"
services:
  simple-proxy:
    image: golang:1.11-stretch
    volumes:
      - .:/go/src/simple-server
    command: "/go/src/simple-server/simpleproxy -url http://consul1:8500"
    ports:
      - "3999:3999"
      - "4000:4000"
    depends_on:
      - consul1
  consulsetup:
    image: golang:1.11-stretch
    volumes:
      - .:/go/src/simple-server
    command: "/go/src/simple-server/testing/consulsetup/setup -url http://consul1:8500"
    depends_on:
      - consul1
      - consul3
      - simple-server
  httpsapp:
    build: ./testing/python_app_https/
  httpapp:
    build: ./testing/python_app_http/
  consul1:
    image: "progrium/consul:latest"
    hostname: "consul1"
    command: "-server -bootstrap-expect 2 -ui-dir /ui"
  consul2:
    image: "progrium/consul:latest"
    hostname: "consul2"
    command: "-server -join consul1"
    depends_on:
      - consul1
  consul3:
    image: "progrium/consul:latest"
    hostname: "consul3"
    command: "-server -join consul1"
    depends_on:
      - consul1
